version: '3'

services:
  database:
    image: postgres:18
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./stomatology_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    image: fastapi:latest
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: database
    working_dir: /app
    entrypoint: ["bash", "-c"]
    command: ["uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/static/doc_photo
    depends_on:
      database:
        condition: service_healthy


  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    

  celery:
    image: fastapi:latest
    env_file:
      - .env
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      CELERY_BROKER_URL: redis://redis:6379/0
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    working_dir: /app
    entrypoint: ["bash", "-c"]
    command: ["celery -A app.tasks.celery worker --loglevel=info"]
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy

volumes:
  db_data:
  media_data: