"""add new fields to the service table

Revision ID: 3bd70b041c7b
Revises: ebb907243c1c
Create Date: 2026-01-16 18:27:30.462420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd70b041c7b'
down_revision: Union[str, Sequence[str], None] = 'ebb907243c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('name', sa.String(), nullable=False))
    op.add_column('services', sa.Column('desctiption', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'desctiption')
    op.drop_column('services', 'name')
    # ### end Alembic commands ###
