"""edit fields to the doctor table

Revision ID: 8ce4181d6b45
Revises: 8d97c9d7e891
Create Date: 2026-01-17 20:17:04.905072

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ce4181d6b45'
down_revision: Union[str, Sequence[str], None] = '8d97c9d7e891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('dentistry_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'doctors', 'dentistry', ['dentistry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'dentistry_id')
    # ### end Alembic commands ###
