"""edit fields to the service table

Revision ID: 8d97c9d7e891
Revises: 3bd70b041c7b
Create Date: 2026-01-16 18:36:35.461652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d97c9d7e891'
down_revision: Union[str, Sequence[str], None] = '3bd70b041c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('services', 'desctiption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('desctiption', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('services', 'description')
    # ### end Alembic commands ###
