"""edit servise model

Revision ID: a189bd8569dd
Revises: 6c56ffb32a22
Create Date: 2026-01-26 11:34:44.086526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a189bd8569dd'
down_revision: Union[str, Sequence[str], None] = '6c56ffb32a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'requires_consultation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('requires_consultation', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
